
 spring:
    #thymeleaf
    thymeleaf:
       cache: false # 关闭页面缓存
       encoding: UTF-8 # 模板编码
       prefix: classpath:/templates/  # 页面映射路径
       suffix: .html # 试图后的后缀
       mode: HTML5 # 模板模式
    #druid
    datasource:
       url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncodeing=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
       username: root
       password: 123456
       driver-class-name: com.mysql.cj.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
       filters: stat
       maxActive: 1000
       initialSize: 100
       maxWait: 60000
       minIdle: 500
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20
#mybatis
 mybatis: 
    type-aliases-pakeage: com.imooc.miaosha.pojo
    configuration:
       map-underscore-to-camel-case: true   #开启驼峰命名
       default-fetch-size: 100   #
       default-statement-timeout: 3000   #
    mapperLocations: classpath:com/imooc/miaosha/dao/*xml
#redis
 redis:
    host: 192.168.31.101
    port: 6379
    timeout: 10
    password: 123456
    pool:
       maxTotal: 1000
       maxIdle: 500
       maxWait: 500

 